const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let patients=JSON.parse(localStorage.getItem('fcPatients')||'null')||[
 {id:'00000001',n:'Jordan Olsen',i:'JO',age:'34 · M',email:'jordan.olsen@email.com',mrn:'MRN-10248',last:'Today, 10:30 AM',checkup:'2026-06-18T10:30',concern:'Seasonal allergies',status:'Checked in'},
 {id:'00000002',n:'Samira Patel',i:'SP',age:'42 · F',email:'samira.patel@email.com',mrn:'MRN-10231',last:'Today, 9:15 AM',checkup:'2026-06-18T09:15',concern:'Diabetes follow-up',status:'In consultation'},
 {id:'00000003',n:'Marcus Chen',i:'MC',age:'57 · M',email:'marcus.chen@email.com',mrn:'MRN-10192',last:'Yesterday',checkup:'2026-06-24T11:00',concern:'Annual physical',status:'Complete'},
 {id:'00000004',n:'Elena Rossi',i:'ER',age:'29 · F',email:'elena.rossi@email.com',mrn:'MRN-10172',last:'Jun 16, 2026',checkup:'2026-06-25T14:30',concern:'Migraine',status:'Complete'},
 {id:'00000005',n:'David Kim',i:'DK',age:'61 · M',email:'david.kim@email.com',mrn:'MRN-10164',last:'Jun 15, 2026',checkup:'2026-06-26T09:45',concern:'Blood pressure',status:'Complete'}
];
let nextPatientId=Number(localStorage.getItem('fcNextPatientId')||'0');
patients.forEach((p,index)=>{if(!p.id)p.id=String(index+1).padStart(8,'0');if(!p.email)p.email=`${p.n.toLowerCase().replace(/\s+/g,'.')}@email.com`;if(!p.phone)p.phone='(415) 555-0100';if(!p.checkup)p.checkup='2026-06-25T10:00'});
nextPatientId=Math.max(nextPatientId,...patients.map(p=>Number(p.id)||0))+1;
const schedule=[['9:00','Jordan Olsen','Follow-up visit','mint'],['9:30','Samira Patel','Diabetes management','blue'],['10:15','Marcus Chen','Annual physical','amber'],['11:00','Elena Rossi','Telehealth consultation','mint'],['11:30','David Kim','Blood pressure check','blue']];
let appointments=JSON.parse(localStorage.getItem('fcAppointments')||'null')||[
 {id:'APT-001',patient:'Jordan Olsen',time:'2026-06-18T09:00',type:'Follow-up visit'},
 {id:'APT-002',patient:'Samira Patel',time:'2026-06-18T09:30',type:'Diabetes management'},
 {id:'APT-003',patient:'Marcus Chen',time:'2026-06-18T10:15',type:'Annual physical'},
 {id:'APT-004',patient:'Elena Rossi',time:'2026-06-16T11:00',type:'Telehealth consultation'}
];
if(!appointments.some(a=>a.patient==='Elena Rossi'))appointments.push({id:'APT-004',patient:'Elena Rossi',time:'2026-06-16T11:00',type:'Telehealth consultation'});
const prescriptions=[
 {patient:'Jordan Olsen',medication:'Cetirizine 10 mg tablet',directions:'Take 1 tablet by mouth daily',status:'Active',date:'Jun 18, 2026',kind:'active',prescriber:'Dr. Alex Morgan',refills:'2 refills remaining'},
 {patient:'Samira Patel',medication:'Metformin 500 mg tablet',directions:'Take 1 tablet twice daily with meals',status:'Renewal due',date:'Jun 12, 2026',kind:'pending',prescriber:'Dr. Alex Morgan',refills:'No refills remaining'},
 {patient:'Marcus Chen',medication:'Lisinopril 20 mg tablet',directions:'Take 1 tablet by mouth daily',status:'Active',date:'Jun 10, 2026',kind:'active',prescriber:'Dr. Alex Morgan',refills:'3 refills remaining'},
 {patient:'Elena Rossi',medication:'Sumatriptan 50 mg tablet',directions:'Take 1 tablet at the onset of migraine',status:'Renewal due',date:'Jun 08, 2026',kind:'pending',prescriber:'Dr. Alex Morgan',refills:'No refills remaining'},
 {patient:'David Kim',medication:'Amlodipine 5 mg tablet',directions:'Take 1 tablet by mouth daily',status:'Discontinued',date:'May 26, 2026',kind:'history',prescriber:'Dr. Alex Morgan',refills:'Prescription closed'},
 {patient:'Jordan Olsen',medication:'Fluticasone nasal spray',directions:'2 sprays in each nostril daily',status:'Completed',date:'May 14, 2026',kind:'history',prescriber:'Dr. Alex Morgan',refills:'Treatment complete'}
];
let invoices=[
 {id:'INV-2026-184',patient:'Jordan Olsen',payer:'Allied Health',amount:'$165.00',status:'Paid',date:'Jun 18, 2026',service:'Follow-up visit'},
 {id:'INV-2026-183',patient:'Samira Patel',payer:'BlueCross PPO',amount:'$240.00',status:'Pending',date:'Jun 18, 2026',service:'Diabetes management'},
 {id:'INV-2026-182',patient:'Marcus Chen',payer:'Self pay',amount:'$320.00',status:'Sent',date:'Jun 17, 2026',service:'Annual physical'},
 {id:'INV-2026-181',patient:'Elena Rossi',payer:'UnitedCare',amount:'$145.00',status:'Partial paid',date:'Jun 16, 2026',service:'Telehealth consultation'}
];
let calendarDate=new Date(2026,5,18),calendarView='day';
function savePatients(){localStorage.setItem('fcPatients',JSON.stringify(patients));localStorage.setItem('fcNextPatientId',String(nextPatientId))}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
function patientRow(p,recent=false){let time=new Date(p.checkup).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});return recent?`<div class="table-row"><div class="patient-name"><div class="avatar">${p.i}</div>${p.n}</div><span>${p.last}</span><span>${p.concern}</span><span class="pill ${p.status==='Complete'?'gray':'green'}">${p.status}</span><button class="more">•••</button></div>`:`<div class="directory-row patient-detail" data-name="${p.n}"><div class="patient-name"><div class="avatar">${p.i}</div><div>${p.n}<small>ID ${p.id} · ${p.age} · ${p.mrn}</small><small>${p.email} · ${p.phone}</small></div></div><span>${p.last}<small class="checkup">Check-up: ${time}</small></span><span>${p.concern}</span><span class="pill ${p.status==='Complete'?'gray':'green'}">${p.status}</span><button class="more delete-patient" data-name="${p.n}" title="Delete patient">×</button></div>`}
function bindPatientRows(){$$('.patient-detail').forEach(row=>row.onclick=e=>{if(!e.target.closest('.delete-patient'))openPatientDetails(row.dataset.name)});$$('.delete-patient').forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm(`Remove ${b.dataset.name} from the patient directory?`)){patients=patients.filter(p=>p.n!==b.dataset.name);savePatients();renderPatients();toast('Patient removed from directory')}})}
function renderPatients(){ $('#recentPatients').innerHTML=patients.slice(0,4).map(p=>patientRow(p,true)).join(''); $('#patientList').innerHTML=patients.map(p=>patientRow(p)).join(''); $('#patientCount').textContent=`(${patients.length})`;bindPatientRows()}
function renderSchedule(){$('#scheduleList').innerHTML=schedule.map(x=>`<div class="appt"><time><b>${x[0]}</b>AM</time><span class="line-dot ${x[3]==='blue'?'blue-dot':x[3]==='amber'?'amber-dot':''}"></span><div class="appt-info"><b>${x[1]}</b><p>${x[2]}</p></div><span class="appt-tag">${x[3]==='blue'?'In person':x[3]==='amber'?'Annual':'Follow-up'}</span></div>`).join('')}
function renderCalendar(){let label=calendarDate.toLocaleString('en-US',{month:'long',year:'numeric'}),view=$('#calendarViewport');$('#calendarLabel').textContent=label;$$('.calendar-view').forEach(x=>x.classList.toggle('active',x.dataset.calendarView===calendarView));if(calendarView==='month'){let first=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay()),cells=Array.from({length:42},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let inMonth=d.getMonth()===calendarDate.getMonth(),dayAppointments=appointments.filter(a=>new Date(a.time).toDateString()===d.toDateString()),events=dayAppointments.map(a=>`<button class="month-event calendar-appointment" data-appointment="${a.id}">${a.patient}</button>`).join('');return `<div class="month-day ${inMonth?'':'outside'} ${d.getDate()===18&&inMonth?'selected-day':''}"><b>${d.getDate()}</b>${events}</div>`}).join('');view.innerHTML=`<div class="month-weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="month-grid">${cells}</div>`}else{let ev=[['Jordan Olsen','Follow-up',75,'event-mint'],['Samira Patel','Diabetes management',165,'event-blue'],['Marcus Chen','Annual physical',285,'event-peach']],days=calendarView==='day'?['MON 15','TUE 16','WED 17','THU 18','FRI 19']:['SUN 14','MON 15','TUE 16','WED 17','THU 18','FRI 19','SAT 20'],colCount=days.length;let cols=Array.from({length:colCount},(_,i)=>`<div class="cal-col ${days[i].includes('18')?'today-bg':''}">${days[i].includes('18')?ev.map(e=>`<button class="cal-event calendar-appointment ${e[3]}" style="top:${e[2]}px;height:57px"><b>${e[0]}</b>${e[1]}</button>`).join(''):i===1?`<button class="cal-event calendar-appointment event-blue" style="top:235px;height:55px"><b>Elena Rossi</b>Telehealth</button>`:''}</div>`).join('');view.innerHTML=`<div class="weekdays" style="grid-template-columns:repeat(${colCount},1fr)">${days.map(x=>`<span class="${x.includes('18')?'today-col':''}">${x}</span>`).join('')}</div><div class="calendar-body" style="grid-template-columns:62px repeat(${colCount},1fr)"><div>${['8 AM','9 AM','10 AM','11 AM','12 PM','1 PM','2 PM'].map(t=>`<div class="time-slot">${t}</div>`).join('')}</div>${cols}</div>`}$$('.calendar-appointment').forEach(el=>el.onclick=()=>{let id=el.dataset.appointment||appointments.find(a=>a.patient===el.querySelector('b').textContent)?.id;if(id)openAppointmentEditor(id)})}
function saveAppointments(){localStorage.setItem('fcAppointments',JSON.stringify(appointments))}
function renderAppointmentList(){$('#appointmentList').innerHTML=appointments.sort((a,b)=>a.time.localeCompare(b.time)).map(a=>`<button class="appointment-row" data-appointment="${a.id}"><span class="appt-date">${new Date(a.time).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span><span><b>${a.patient}</b><small>${a.type} · ${a.id}</small></span><span class="pill green">Scheduled</span><span>Manage →</span></button>`).join('')||'<p class="empty-state">No upcoming appointments.</p>';$$('.appointment-row').forEach(row=>row.onclick=()=>openAppointmentEditor(row.dataset.appointment))}
function openAppointmentEditor(id){let a=appointments.find(x=>x.id===id),f=$('#modalFields');$('#modalTitle').textContent=`Manage ${a.id}`;f.innerHTML=`<p class="form-note">Change appointment information or cancel this appointment.</p><label>Patient<select name="name">${patients.map(p=>`<option ${p.n===a.patient?'selected':''}>${p.n}</option>`).join('')}</select></label><label>Date & time<input name="time" type="datetime-local" value="${a.time}" required></label><label>Visit type<select name="type"><option ${a.type==='Follow-up visit'?'selected':''}>Follow-up visit</option><option ${a.type==='Annual physical'?'selected':''}>Annual physical</option><option ${a.type==='Telehealth consultation'?'selected':''}>Telehealth consultation</option><option ${a.type==='Diabetes management'?'selected':''}>Diabetes management</option></select></label><button type="button" class="danger-btn modal-cancel" id="cancelAppointment">Cancel appointment</button>`;$('#modal').dataset.type='edit-appointment';$('#modal').dataset.appointmentId=id;$('#modal').classList.remove('hidden');$('#cancelAppointment').onclick=()=>{if(confirm(`Cancel ${a.id} for ${a.patient}?`)){appointments=appointments.filter(x=>x.id!==id);saveAppointments();renderAppointmentList();$('#modal').classList.add('hidden');toast(`${id} cancelled`)}}}
function renderInvoices(filter='All'){let list=filter==='All'?invoices:invoices.filter(x=>x.status===filter);$('#invoiceList').innerHTML=list.map(x=>`<div class="invoice invoice-row" data-invoice="${invoices.indexOf(x)}"><button class="invoice-details"><div><b>${x.patient}</b><p>${x.id} · ${x.payer}</p></div><span>${x.amount}</span><span class="pill ${x.status==='Paid'?'green':x.status==='Pending'?'amber':'gray'}">${x.status}</span><span>${x.date}</span></button><button class="delete-invoice" data-invoice="${invoices.indexOf(x)}" title="Delete invoice">×</button></div>`).join('')||'<p class="empty-state">No invoices in this view.</p>';$$('.invoice-details').forEach(row=>row.onclick=()=>openInvoiceDetails(invoices[row.parentElement.dataset.invoice]));$$('.delete-invoice').forEach(btn=>btn.onclick=()=>{let invoice=invoices[btn.dataset.invoice];if(confirm(`Delete ${invoice.id} for ${invoice.patient}? This cannot be undone.`)){invoices.splice(Number(btn.dataset.invoice),1);renderInvoices(filter);renderReportInvoices();toast(`${invoice.id} deleted`)}})}
function openInvoiceDetails(invoice){let f=$('#modalFields');$('#modalTitle').textContent=invoice.id;f.innerHTML=`<div class="detail-banner"><div class="profile-avatar">$</div><div><b>${invoice.patient}</b><p>${invoice.status} · ${invoice.amount}</p></div></div><div class="detail-grid"><div><small>Service</small><b>${invoice.service}</b></div><div><small>Invoice status</small><b>${invoice.status}</b></div><div><small>Payer</small><b>${invoice.payer}</b></div><div><small>Invoice date</small><b>${invoice.date}</b></div><div><small>Amount due</small><b>${invoice.amount}</b></div></div>`;$('#modal').dataset.type='details';$('#modal').classList.remove('hidden')}
function openNewInvoice(){let f=$('#modalFields');$('#modalTitle').textContent='Create invoice';f.innerHTML=`<label>Patient<select name="patient" required>${patients.map(p=>`<option>${p.n}</option>`).join('')}</select></label><label>Service<input name="service" required placeholder="e.g. Follow-up visit"></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required placeholder="0.00"></label><label>Payer<select name="payer"><option>Self pay</option><option>Allied Health</option><option>BlueCross PPO</option><option>UnitedCare</option></select></label><label>Status<select name="status"><option>Draft</option><option>Sent</option><option>Pending</option></select></label>`;$('#modal').dataset.type='new-invoice';$('#modal').classList.remove('hidden')}
function renderReportInvoices(filter='unpaid'){let list=filter==='unpaid'?invoices.filter(x=>x.status!=='Paid'&&x.status!=='Partial paid'):invoices.filter(x=>x.status===filter);$('#unpaidCount').textContent=`(${invoices.filter(x=>x.status!=='Paid'&&x.status!=='Partial paid').length})`;$('#paidCount').textContent=`(${invoices.filter(x=>x.status==='Paid').length})`;$('#partialCount').textContent=`(${invoices.filter(x=>x.status==='Partial paid').length})`;$('#reportInvoiceList').innerHTML=list.map(x=>`<button class="report-invoice" data-invoice="${invoices.indexOf(x)}"><span><b>${x.patient}</b><small>${x.id} · ${x.payer}</small></span><b>${x.amount}</b><span class="pill ${x.status==='Paid'?'green':x.status==='Partial paid'?'amber':'gray'}">${x.status}</span><span>View →</span></button>`).join('')||'<p class="empty-state">No invoices in this status.</p>';$$('.report-invoice').forEach(row=>row.onclick=()=>openInvoiceDetails(invoices[row.dataset.invoice]));$$('.invoice-status').forEach(tab=>tab.onclick=()=>{renderReportInvoices(tab.dataset.reportInvoice);$$('.invoice-status').forEach(x=>x.classList.toggle('active',x===tab))})}
function renderPrescriptions(filter='active'){let list=filter==='active'?prescriptions.filter(x=>x.kind==='active'):prescriptions.filter(x=>x.kind===filter);$('#rxList').innerHTML=list.map((x,i)=>`<button class="rx rx-row" data-rx="${prescriptions.indexOf(x)}"><div class="rx-icon">Rx</div><div><b>${x.medication}</b><p>${x.patient} · ${x.directions}</p></div><span class="pill ${x.kind==='active'?'green':x.kind==='pending'?'amber':'gray'}">${x.status}</span><small>${x.date}</small><span class="more">•••</span></button>`).join('')||'<p class="empty-state">No prescriptions in this view.</p>';$$('.rx-row').forEach(row=>row.onclick=()=>openPrescriptionDetails(prescriptions[row.dataset.rx]));$$('.rx-tab').forEach(tab=>tab.onclick=()=>{renderPrescriptions(tab.dataset.rxFilter);$$('.rx-tab').forEach(x=>x.classList.toggle('active',x===tab))})}
function openPrescriptionDetails(rx){let p=patients.find(x=>x.n===rx.patient),f=$('#modalFields'),rxIndex=prescriptions.indexOf(rx);$('#modalTitle').textContent=rx.medication;f.innerHTML=`<div class="detail-banner"><div class="profile-avatar">${p?p.i:initials(rx.patient)}</div><div><b>${rx.patient}</b><p>${rx.status} prescription</p></div></div><div class="detail-grid"><div><small>Directions</small><b>${rx.directions}</b></div><div><small>Prescription status</small><b>${rx.status}</b></div><div><small>Prescriber</small><b>${rx.prescriber}</b></div><div><small>Refills</small><b>${rx.refills}</b></div><div><small>Last issued</small><b>${rx.date}</b></div></div>${rx.pdf?`<div class="attachment-section"><small>Attached prescription PDF</small><button class="pdf-preview" id="pdfPreview" title="Open ${rx.pdf}"><span>PDF</span><b>${rx.pdf}</b></button></div>`:''}<div style="display:flex;gap:10px;margin-top:20px"><button type="button" class="secondary" id="editPrescription">Edit prescription</button><button type="button" class="danger-btn" id="deletePrescription">Delete</button></div>`;$('#modal').dataset.type='details';$('#modal').classList.remove('hidden');if(rx.pdfUrl)$('#pdfPreview').onclick=()=>window.open(rx.pdfUrl,'_blank','noopener');$('#editPrescription').onclick=()=>openPrescriptionEditor(rxIndex);$('#deletePrescription').onclick=()=>{if(confirm(`Delete ${rx.medication} for ${rx.patient}?`)){prescriptions.splice(rxIndex,1);renderPrescriptions();$('#modal').classList.add('hidden');toast('Prescription deleted')}}}
function openPrescriptionEditor(index){let rx=prescriptions[index],f=$('#modalFields');$('#modalTitle').textContent='Edit prescription';f.innerHTML=`<label>Patient<select name="patient">${patients.map(p=>`<option ${p.n===rx.patient?'selected':''}>${p.n}</option>`).join('')}</select></label><label>Medication<input name="medication" value="${rx.medication}" required></label><label>Directions<input name="directions" value="${rx.directions}" required></label><label>Status<select name="status"><option ${rx.status==='Active'?'selected':''}>Active</option><option ${rx.status==='Renewal due'?'selected':''}>Renewal due</option><option ${rx.status==='Completed'?'selected':''}>Completed</option></select></label><label>Refills<input name="refills" value="${rx.refills}" required></label><label>Replace prescription PDF <input name="pdf" type="file" accept="application/pdf,.pdf"></label>`;$('#modal').dataset.type='edit-rx';$('#modal').dataset.rxIndex=index;$('#modal').classList.remove('hidden')}
function openNewPrescription(){let f=$('#modalFields');$('#modalTitle').textContent='New prescription';f.innerHTML=`<label>Patient<select name="patient" required>${patients.map(p=>`<option>${p.n}</option>`).join('')}</select></label><label>Medication<input name="medication" required placeholder="e.g. Amoxicillin 500 mg capsule"></label><label>Directions<input name="directions" required placeholder="e.g. Take 1 capsule twice daily"></label><label>Refills<select name="refills"><option>0 refills</option><option>1 refill</option><option>2 refills</option><option>3 refills</option></select></label><label>Prescription PDF <input name="pdf" type="file" accept="application/pdf,.pdf"></label>`;$('#modal').dataset.type='new-rx';$('#modal').classList.remove('hidden')}
function page(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-item[data-page]').forEach(p=>p.classList.toggle('active',p.dataset.page===id));$('#pageTitle').textContent=id==='medical'?'Medical records':id[0].toUpperCase()+id.slice(1);window.scrollTo(0,0)}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2700)}
$$('[data-auth]').forEach(b=>b.onclick=()=>{$('#signInForm').classList.toggle('hidden',b.dataset.auth==='signup');$('#signUpForm').classList.toggle('hidden',b.dataset.auth==='signin');$('#authError').classList.add('hidden')});
$('#signUpForm').onsubmit=e=>{e.preventDefault();let name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim(),pw=$('#signupPassword').value,confirmPw=$('#confirmPassword').value,err=$('#authError');if(pw!==confirmPw){err.textContent='Passwords do not match. Please try again.';err.classList.remove('hidden');return}localStorage.setItem('fcUser',JSON.stringify({name,email,pw}));err.classList.add('hidden');$('#signUpForm').reset();$('#signUpForm').classList.add('hidden');$('#signInForm').classList.remove('hidden');toast('Account created — please sign in')};
$('#signInForm').onsubmit=e=>{e.preventDefault();let u=JSON.parse(localStorage.getItem('fcUser')||'null'),email=$('#loginEmail').value,pw=$('#loginPassword').value;if(!u){u={name:'Alex Morgan',email:'alex@northstarclinic.com',pw:'fusion123'}}if(email===u.email&&pw===u.pw){localStorage.setItem('fcSession','true');startApp(u)}else{toast('Incorrect email or password. Try alex@northstarclinic.com / fusion123')}};
function startApp(u){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');let i=initials(u.name),firstName=u.name.trim().split(/\s+/)[0]||'there';$$('.avatar').forEach(a=>{if(a.textContent==='AM')a.textContent=i});$('#greetingName').textContent=firstName;$('#profileName').value=u.name;$('#profileEmail').value=u.email;$('#profileAvatar').textContent=i;renderPatients();renderSchedule();renderCalendar();renderAppointmentList();renderInvoices();renderPrescriptions();renderReportInvoices()}
function openModal(type){let f=$('#modalFields'),title=$('#modalTitle');title.textContent=type==='patient'?'Add a new patient':'Schedule appointment';f.innerHTML=type==='patient'?`<label>Patient ID<input value="${String(nextPatientId).padStart(8,'0')}" readonly aria-label="Patient ID"></label><label>Full name<input name="name" required placeholder="Patient name"></label><label>Email address<input name="email" type="email" required placeholder="patient@email.com"></label><label>Phone number<input name="phone" type="tel" required placeholder="(415) 555-0100"></label><label>Date of birth<input name="age" required placeholder="e.g. 34 · F"></label><label>Status<select name="status"><option>New</option><option>Checked in</option><option>In consultation</option><option>Complete</option></select></label><label>Primary concern<input name="concern" required placeholder="Reason for visit"></label><label>Check-up time<input name="checkup" type="datetime-local" required></label>`:`<label>Patient<select name="name" required>${patients.map(p=>`<option value="${p.n}">${p.n} · ${p.id}</option>`).join('')}</select></label><label>Date & time<input name="time" type="datetime-local" required></label><label>Visit type<select name="type"><option>Follow-up visit</option><option>Annual physical</option><option>Telehealth consultation</option></select></label>`;$('#modal').dataset.type=type;$('#modal').classList.remove('hidden')}
function openPatientDetails(name){let p=patients.find(x=>x.n===name),f=$('#modalFields'),documents=(p.files||[]);$('#modalTitle').textContent=`Edit ${p.n}`;f.innerHTML=`<div class="detail-banner"><div class="profile-avatar">${p.i}</div><div><b>Patient ID ${p.id}</b><p>Edit patient information below</p></div></div><label>Patient ID<input value="${p.id}" readonly></label><label>Full name<input name="name" value="${p.n}" required></label><label>Email address<input name="email" type="email" value="${p.email}" required></label><label>Phone number<input name="phone" type="tel" value="${p.phone}" required></label><label>Patient details<input name="age" value="${p.age}" required></label><label>Medical record no.<input name="mrn" value="${p.mrn}" required></label><label>Status<select name="status"><option ${p.status==='New'?'selected':''}>New</option><option ${p.status==='Checked in'?'selected':''}>Checked in</option><option ${p.status==='In consultation'?'selected':''}>In consultation</option><option ${p.status==='Complete'?'selected':''}>Complete</option></select></label><label>Primary concern<input name="concern" value="${p.concern}" required></label><label>Next check-up<input name="checkup" type="datetime-local" value="${p.checkup}" required></label><div class="attachment-section"><small>Patient documents</small><div id="patientDocuments" style="display:flex;gap:9px;flex-wrap:wrap">${documents.map((doc,i)=>`<div><button type="button" class="pdf-preview patient-file" data-file="${i}" title="Open ${doc.name}"><span>${doc.name.split('.').pop().toUpperCase().slice(0,4)}</span><b>${doc.name}</b></button><button type="button" class="link-btn delete-patient-file" data-file="${i}">Delete</button></div>`).join('')||'<small>No documents uploaded yet.</small>'}</div></div><label>Upload or replace patient document<input name="patientFile" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></label>`;$('#modal').dataset.type='edit-patient';$('#modal').dataset.patientId=p.id;$('#modal').classList.remove('hidden');$$('.patient-file').forEach(btn=>btn.onclick=()=>{let doc=p.files[Number(btn.dataset.file)];if(doc.url)window.open(doc.url,'_blank','noopener');else toast('This file needs to be uploaded again after refreshing the app.')});$$('.delete-patient-file').forEach(btn=>btn.onclick=()=>{p.files.splice(Number(btn.dataset.file),1);savePatients();openPatientDetails(p.n);toast('Patient document deleted')})}
function openRecordEditor(name){let p=patients.find(x=>x.n===name)||patients[0],f=$('#modalFields');$('#modalTitle').textContent=`Update ${p.n}'s record`;f.innerHTML=`<p class="form-note">Add a clinical note or update the scheduled check-up time.</p><label>Check-up time<input name="checkup" type="datetime-local" value="${p.checkup}" required></label><label>Clinical note<textarea name="note" rows="5" placeholder="Write a progress note, care instruction, or follow-up detail..."></textarea></label>`;$('#modal').dataset.type='record';$('#modal').dataset.patient=p.n;$('#modal').classList.remove('hidden')}
$('#addPatient').onclick=()=>openModal('patient');$('#addAppointment').onclick=()=>openModal('appointment');$('#newPrescription').onclick=openNewPrescription;$('.close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};$('#modalForm').onsubmit=e=>{e.preventDefault();let d=new FormData(e.target),type=$('#modal').dataset.type;if(type==='new-invoice'){let id=`INV-2026-${185+invoices.length}`;invoices.unshift({id,patient:d.get('patient'),payer:d.get('payer'),amount:`$${Number(d.get('amount')).toFixed(2)}`,status:d.get('status'),date:'Today',service:d.get('service')});renderInvoices();renderReportInvoices();$('#invoiceFilter').dataset.status='All';$('#invoiceFilter').textContent='All status ⌄';toast(`${id} created for ${d.get('patient')}`)}else if(type==='edit-patient'){let p=patients.find(x=>x.id===$('#modal').dataset.patientId),oldName=p.n;p.n=d.get('name').trim();p.i=initials(p.n);p.email=d.get('email').trim();p.age=d.get('age').trim();p.mrn=d.get('mrn').trim();p.status=d.get('status');p.concern=d.get('concern').trim();p.checkup=d.get('checkup');savePatients();renderPatients();toast(`${oldName}'s patient information was updated`)}else if(type==='patient'){let n=d.get('name').trim(),id=String(nextPatientId).padStart(8,'0');patients.unshift({id,n,i:initials(n),email:d.get('email'),age:d.get('age'),mrn:'MRN-'+(10249+nextPatientId),last:'Not yet seen',checkup:d.get('checkup'),concern:d.get('concern'),status:d.get('status')});nextPatientId++;savePatients();renderPatients();page('patients');toast(`${n} added with Patient ID ${id}`)}else if(type==='record'){let p=patients.find(x=>x.n===$('#modal').dataset.patient);p.checkup=d.get('checkup');if(d.get('note').trim())p.note=d.get('note').trim();savePatients();renderPatients();toast(`${p.n}'s record and check-up time were updated`)}else if(type==='new-rx'){prescriptions.unshift({patient:d.get('patient'),medication:d.get('medication'),directions:d.get('directions'),status:'Active',date:'Today',kind:'active',prescriber:'Dr. Alex Morgan',refills:d.get('refills')+' remaining'});renderPrescriptions();$$('.rx-tab').forEach(x=>x.classList.toggle('active',x.dataset.rxFilter==='active'));toast(`Prescription created for ${d.get('patient')}`)}else if(type==='details'){$('#modal').classList.add('hidden');return}else{let p=patients.find(x=>x.n===d.get('name'));if(p){p.checkup=d.get('time');savePatients();renderPatients()}toast(`Appointment scheduled for ${d.get('name')}`)}$('#modal').classList.add('hidden');e.target.reset()};
$('#newInvoice').onclick=openNewInvoice;$('#invoiceFilter').onclick=()=>{let next=$('#invoiceFilter').dataset.status==='Pending'?'All':$('#invoiceFilter').dataset.status==='Paid'?'Pending':'Paid';$('#invoiceFilter').dataset.status=next;$('#invoiceFilter').textContent=`${next==='All'?'All status':next} ⌄`;renderInvoices(next)};$$('.billing-stat').forEach(card=>card.onclick=()=>{let filter=card.dataset.billingFilter;if(filter==='claims'){toast('Insurance claims: 28 submitted · 92% clean claim rate');return}$('#invoiceFilter').dataset.status=filter;$('#invoiceFilter').textContent=`${filter} ⌄`;renderInvoices(filter)});$('#saveProfile').onclick=()=>toast('Profile changes saved');$('#photoUpload').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader;r.onload=()=>{$('#profileAvatar').style.backgroundImage=`url(${r.result})`;$('#profileAvatar').textContent='';toast('Profile photo updated')};r.readAsDataURL(f)}};
$('#logout').onclick=()=>{localStorage.removeItem('fcSession');$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');$('#loginPassword').value='';page('dashboard');toast('You have been signed out')};
$('#patientSearch').oninput=e=>{let q=e.target.value.toLowerCase();$('#patientList').innerHTML=patients.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q)).map(p=>patientRow(p)).join('');bindPatientRows()};
$$('.record').forEach(row=>row.onclick=()=>openRecordEditor(row.querySelector('b').textContent));
$('#calendarPrev').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()};$('#calendarNext').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()};$('#calendarToday').onclick=()=>{calendarDate=new Date(2026,5,18);renderCalendar()};$$('.calendar-view').forEach(btn=>btn.onclick=()=>{calendarView=btn.dataset.calendarView;renderCalendar()});
function openReportDetails(name){let details={"Patient visits":['Patient visits','The clinic has completed 174 visits this month, up 12.4% from the prior period. The strongest booking day was June 12 with 17 completed visits.'],"Top visit types":['Top visit types','Annual wellness visits lead at 32%, followed by follow-up care at 26%. This breakdown helps with staffing and care-planning decisions.'],"Monthly practice summary":['Monthly practice summary','A concise snapshot of patient volume, appointments, outstanding billing, and clinical task completion for June 2026.'],"Patient demographics":['Patient demographics','Review patient population trends by age group, care need, and visit frequency to support service planning.'],"Revenue by payer":['Revenue by payer','Allied Health contributes 38% of revenue, BlueCross PPO 29%, UnitedCare 21%, and self-pay 12%.']}[name]||[name,'This interactive report is ready for review.'];$('#modalTitle').textContent=details[0];$('#modalFields').innerHTML=`<div class="report-modal"><p class="eyebrow teal">REPORT DETAILS</p><h3>${details[0]}</h3><p>${details[1]}</p><div class="report-highlight"><b>June 2026</b><span>Updated today</span></div></div>`;$('#modal').dataset.type='details';$('#modal').classList.remove('hidden')}
$$('.report-click').forEach(item=>item.onclick=()=>openReportDetails(item.dataset.report));let reportPeriods=['June 2026','May 2026','April 2026'];$('#reportPeriod').onclick=()=>{let i=(reportPeriods.indexOf($('#reportPeriod').dataset.period||'June 2026')+1)%reportPeriods.length;$('#reportPeriod').dataset.period=reportPeriods[i];$('#reportPeriod').textContent=`${reportPeriods[i]} ⌄`;toast(`Showing report data for ${reportPeriods[i]}`)};
renderCalendar=function(){let view=$('#calendarViewport'),sameDay=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();$('#calendarLabel').textContent=calendarDate.toLocaleString('en-US',{month:'long',year:'numeric'});$$('.calendar-view').forEach(x=>x.classList.toggle('active',x.dataset.calendarView===calendarView));if(calendarView==='month'){let first=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay());let cells=Array.from({length:42},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let dayAppointments=appointments.filter(a=>sameDay(new Date(a.time),d));return `<div class="month-day ${d.getMonth()===calendarDate.getMonth()?'':'outside'}"><b>${d.getDate()}</b>${dayAppointments.map(a=>`<button class="month-event calendar-appointment" data-appointment="${a.id}">${a.patient}</button>`).join('')}</div>`}).join('');view.innerHTML=`<div class="month-weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="month-grid">${cells}</div>`}else{let count=calendarView==='week'?7:5,start=new Date(calendarDate);start.setDate(calendarDate.getDate()-(calendarView==='week'?calendarDate.getDay():(calendarDate.getDay()+6)%7));let dates=Array.from({length:count},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);return d}),labels=dates.map(d=>d.toLocaleString('en-US',{weekday:'short'}).toUpperCase()+' '+d.getDate()),cols=dates.map(d=>{let dayAppointments=appointments.filter(a=>sameDay(new Date(a.time),d));return `<div class="cal-col ${sameDay(d,calendarDate)?'today-bg':''}">${dayAppointments.map((a,i)=>{let time=new Date(a.time),top=Math.max(8,(time.getHours()-8)*68+time.getMinutes()*1.13);return `<button class="cal-event calendar-appointment ${['event-mint','event-blue','event-peach'][i%3]}" data-appointment="${a.id}" style="top:${top}px;height:57px"><b>${a.patient}</b>${a.type}</button>`}).join('')}</div>`}).join('');view.innerHTML=`<div class="weekdays" style="grid-template-columns:repeat(${count},1fr)">${labels.map((x,i)=>`<span class="${sameDay(dates[i],calendarDate)?'today-col':''}">${x}</span>`).join('')}</div><div class="calendar-body" style="grid-template-columns:62px repeat(${count},1fr)"><div>${['8 AM','9 AM','10 AM','11 AM','12 PM','1 PM','2 PM'].map(t=>`<div class="time-slot">${t}</div>`).join('')}</div>${cols}</div>`}$$('.calendar-appointment').forEach(el=>el.onclick=()=>openAppointmentEditor(el.dataset.appointment))};
$('#modalForm').addEventListener('submit',e=>{let type=$('#modal').dataset.type;if(type!=='appointment'&&type!=='edit-appointment')return;e.preventDefault();e.stopImmediatePropagation();let d=new FormData(e.target);if(type==='appointment'){let id=`APT-${String(appointments.length+1).padStart(3,'0')}`;appointments.push({id,patient:d.get('name'),time:d.get('time'),type:d.get('type')});toast(`Appointment ${id} scheduled for ${d.get('name')}`)}else{let a=appointments.find(x=>x.id===$('#modal').dataset.appointmentId);a.patient=d.get('name');a.time=d.get('time');a.type=d.get('type');toast(`${a.id} updated`)}let p=patients.find(x=>x.n===d.get('name'));if(p){p.checkup=d.get('time');savePatients();renderPatients()}calendarDate=new Date(d.get('time'));saveAppointments();renderAppointmentList();renderCalendar();$('#modal').classList.add('hidden');e.target.reset()},true);
$('#modalForm').addEventListener('submit',e=>{if($('#modal').dataset.type!=='new-rx')return;e.preventDefault();e.stopImmediatePropagation();let d=new FormData(e.target),file=d.get('pdf'),hasPdf=file&&file.name;prescriptions.unshift({patient:d.get('patient'),medication:d.get('medication'),directions:d.get('directions'),status:'Active',date:'Today',kind:'active',prescriber:'Dr. Alex Morgan',refills:d.get('refills')+' remaining',pdf:hasPdf?file.name:'',pdfUrl:hasPdf?URL.createObjectURL(file):''});renderPrescriptions();$$('.rx-tab').forEach(x=>x.classList.toggle('active',x.dataset.rxFilter==='active'));$('#modal').classList.add('hidden');e.target.reset();toast(`Prescription created for ${d.get('patient')}`)},true);
$('#modalForm').addEventListener('submit',e=>{if($('#modal').dataset.type!=='edit-rx')return;e.preventDefault();e.stopImmediatePropagation();let d=new FormData(e.target),rx=prescriptions[Number($('#modal').dataset.rxIndex)],file=d.get('pdf');rx.patient=d.get('patient');rx.medication=d.get('medication').trim();rx.directions=d.get('directions').trim();rx.status=d.get('status');rx.kind=rx.status==='Active'?'active':rx.status==='Renewal due'?'pending':'history';rx.refills=d.get('refills').trim();if(file&&file.name){rx.pdf=file.name;rx.pdfUrl=URL.createObjectURL(file)}renderPrescriptions(rx.kind);$$('.rx-tab').forEach(x=>x.classList.toggle('active',x.dataset.rxFilter===rx.kind));$('#modal').classList.add('hidden');e.target.reset();toast('Prescription updated')},true);
$('#modalForm').addEventListener('submit',e=>{if($('#modal').dataset.type!=='edit-patient')return;e.preventDefault();e.stopImmediatePropagation();let d=new FormData(e.target),p=patients.find(x=>x.id===$('#modal').dataset.patientId),file=d.get('patientFile');p.n=d.get('name').trim();p.i=initials(p.n);p.email=d.get('email').trim();p.phone=d.get('phone').trim();p.age=d.get('age').trim();p.mrn=d.get('mrn').trim();p.status=d.get('status');p.concern=d.get('concern').trim();p.checkup=d.get('checkup');if(file&&file.name){p.files=p.files||[];p.files.push({name:file.name,url:URL.createObjectURL(file)})}savePatients();renderPatients();$('#modal').classList.add('hidden');e.target.reset();toast('Patient information and documents saved')},true);
$('#modalForm').addEventListener('submit',e=>{if($('#modal').dataset.type!=='patient')return;e.preventDefault();e.stopImmediatePropagation();let d=new FormData(e.target),n=d.get('name').trim(),id=String(nextPatientId).padStart(8,'0');patients.unshift({id,n,i:initials(n),email:d.get('email').trim(),phone:d.get('phone').trim(),age:d.get('age').trim(),mrn:'MRN-'+(10249+nextPatientId),last:'Not yet seen',checkup:d.get('checkup'),concern:d.get('concern').trim(),status:d.get('status'),files:[]});nextPatientId++;savePatients();renderPatients();page('patients');$('#modal').classList.add('hidden');e.target.reset();toast(`${n} added with Patient ID ${id}`)},true);
savePatients();
saveAppointments();
if(localStorage.getItem('fcSession'))startApp(JSON.parse(localStorage.getItem('fcUser')||'{"name":"Alex Morgan","email":"alex@northstarclinic.com"}'));
